receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

extensions:
  health_check:
    endpoint: :13133
  
exporters:
  kafka/spans:
    brokers: ["kafka:9092"]
    topic: otlp_spans
    encoding: otlp_json
  kafka/metrics:
    brokers: ["kafka:9092"]
    topic: otlp_metrics
    encoding: otlp_json
  kafka/logs:
    brokers: ["kafka:9092"]
    topic: otlp_logs
    encoding: otlp_json
  debug: 
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [kafka/spans]
    metrics:
      receivers: [otlp]
      exporters: [kafka/metrics]
    logs:
      receivers: [otlp]
      exporters: [kafka/logs, debug]
